name: action-cargo-deny
description: Run cargo-deny on your Rust code base
branding:
  icon: slash
  color: red
inputs:
  checks:
    description: The checks to run, or all if omitted.
    required: false
    default: ''
runs:
  using: composite
  steps:
  - name: Ensure runner OS is 64-bit Linux
    run: |
      if [[ "$(uname -s)" != *"Linux"* ]]; then
        echo "::error ::The OS of the runner must be Linux"
        exit 1
      fi
      if [[ "$(uname -p)" != *"x86_64"* ]]; then
        echo "::error ::The OS architecture of the runner must be x86_64"
        exit 1
      fi
    shell: bash
  - name: Install cargo-deny
    run: |
      VERSION=0.10.2
      curl -Lo /tmp/cargo-deny.tar.gz https://github.com/EmbarkStudios/cargo-deny/releases/download/${VERSION}/cargo-deny-${VERSION}-x86_64-unknown-linux-musl.tar.gz
      sudo tar -xv -C /usr/bin --strip-components 1 -f /tmp/cargo-deny.tar.gz cargo-deny-${VERSION}-x86_64-unknown-linux-musl/cargo-deny
      rm /tmp/cargo-deny.tar.gz
    shell: bash
  - name: Install action-cargo-deny
    run: |
      VERSION=0.1.3
      curl -Lo /tmp/action-cargo-deny.tar.gz https://github.com/dnaka91/action-cargo-deny/releases/download/v${VERSION}/action-cargo-deny-v${VERSION}-x86_64-unknown-linux-musl.tar.gz
      sudo tar -xzv -C /usr/bin -f /tmp/action-cargo-deny.tar.gz action-cargo-deny
      rm /tmp/action-cargo-deny.tar.gz
    shell: bash
  - name: Fetch registry
    run: cargo fetch
    shell: bash
  - name: Run cargo-deny
    run: /usr/bin/action-cargo-deny ${{ inputs.checks }}
    shell: bash
